---
# Pre-step
- name: Pre-Step 3 - Collect device info {{ bigip1_target }}
  uri:
    url: https://{{ provider.server }}:{{ provider.server_port }}/mgmt/cm/system/machineid-resolver?$filter=address%20eq%20'{{ bigip1_target }}'
    method: GET
    timeout: "{{ timeout }}"
    validate_certs: "{{ provider.validate_certs }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
    status_code: 200, 202
  register: json_response

- name: Pre-Step 3 - Collect module imported on {{ bigip1_target }} before removal
  set_fact:
    modules: "{{ json_response | json_query(query) 
                | reject('search','BigIPDevice') | list
                | reject('search','fpsfraudprotectionsecurity') | list
                | regex_replace('adc', 'ltm')
                | regex_replace('asmsecurity', 'asm')
                | regex_replace('sharedsecurity', 'security_shared') 
                | regex_replace('networksecurity', 'afm')
                | regex_replace('Access', 'apm')
                | regex_replace('websafesecurity', 'websafe') }}"
  vars: 
    query: 'json.items[0].properties."cm:gui:module"'
    BigIPDevice: '"BigIPDevice",'

- debug:
    var: modules

# Ansible naming => BIG-IQ naming:
# ltm => adc
# asm => asmsecurity
# apm => Access
# afm => networksecurity
# dns => dns
# websafe => websafesecurity
# security_shared => sharedsecurity

- name: Check if apm module provisionned
  set_fact:
    apm: true
  when: '"apm" in modules'

- name: Pre-Step 3 - Collect Access Group name on {{ bigip1_target }} before removal
  set_fact:
    access_group_name: "{{ json_response | json_query(query) }}"
  vars: 
    query: 'json.items[0].properties."cm-access-allBigIpDevices"."cm:access:access-group-name"'
  when: apm is defined

- debug:
    var: access_group_name
  when: apm is defined

# 3. Remove the device {{ bigip1_target }} from BIG-IQ
- name: Step 3 - Remove discovered device {{ bigip1_target }} and its config
  f5networks.f5_modules.bigiq_device_discovery:
    device_address: "{{ bigip1_target }}"
    state: absent
    provider: "{{ provider }}"

# 4. Add back the device {{ bigip1_target }} in BIG-IQ
- name: Step 4 - Add back the device {{ bigip1_target }} and its config - Standalone (no APM)
  f5networks.f5_modules.bigiq_device_discovery:
    device_address: "{{ bigip1_target }}"
    device_port: "{{ device_port }}"
    device_username: "{{ device_username }}"
    device_password: "{{ device_password }}"
    modules: "{{ modules | list }}"
    conflict_policy: "{{ conflict_policy }}"
    device_conflict_policy: "{{ device_conflict_policy }}"
    versioned_conflict_policy: "{{ versioned_conflict_policy }}"
    statistics:
      enable: "{{ enable }}"
      stat_modules: "{{ stat_modules | list }}"
      interval: "{{ interval }}"
      zone: "{{ zone }}"
    provider: "{{ provider }}"
  when: apm is not defined
  ignore_errors: yes

# If BIG-IP has access module provisionned
- name: Step 4 - Add back the device {{ bigip1_target }} and its config - Standalone with APM
  f5networks.f5_modules.bigiq_device_discovery:
    device_address: "{{ bigip1_target }}"
    device_port: "{{ device_port }}"
    device_username: "{{ device_username }}"
    device_password: "{{ device_password }}"
    modules: "{{ modules | list }}"
    conflict_policy: "{{ conflict_policy }}"
    device_conflict_policy: "{{ device_conflict_policy }}"
    versioned_conflict_policy: "{{ versioned_conflict_policy }}"
    access_group_name: "{{ access_group_name }}"
    access_group_first_device: "{{ access_group_first_device }}"
    access_conflict_policy: "{{ access_conflict_policy }}"
    statistics:
      enable: "{{ enable }}"
      stat_modules: "{{ stat_modules | list }}"
      interval: "{{ interval }}"
      zone: "{{ zone }}"
    provider: "{{ provider }}"
  when: apm is defined
  ignore_errors: yes
