---
- name: Verify bigip2_target properly set
  fail:
    msg: "The variable 'bigip2_target' is not defined"
  when: bigip2_target is undefined

- name: Get details for device {{ bigip1_target }}
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/shared/resolver/device-groups/cm-adccore-allbigipDevices/devices?$filter=address%20eq%20'{{ bigip1_target }}...{{ bigip1_target }}'"
    method: GET
    timeout: "{{ timeout }}"
    validate_certs: "{{ provider.validate_certs }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
  register: json_response

- name: Get the clusterName for {{ bigip1_target }}
  set_fact:
    clusterName_device1: "{{ json_response | json_query(query) | join(' ') }}"
  vars: 
    query: "json.items[?address=='{{ bigip1_target }}'].properties.clusterName"

- debug:
    var: clusterName_device1

- name: Get details for device {{ bigip2_target }}
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/shared/resolver/device-groups/cm-adccore-allbigipDevices/devices?$filter=address%20eq%20'{{ bigip2_target }}...{{ bigip2_target }}'"
    method: GET
    timeout: "{{ timeout }}"
    validate_certs: "{{ provider.validate_certs }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
  register: json_response

- name: Get the clusterName for {{ bigip2_target }}
  set_fact:
    clusterName_device2: "{{ json_response | json_query(query) | join(' ') }}"
  vars: 
    query: "json.items[?address=='{{ bigip2_target }}'].properties.clusterName"

- debug:
    var: clusterName_device2

- name: Check if both BIG-IP devices belong to the same cluster
  fail:
    msg: "{{ bigip1_target }} must be in the same cluster on BIG-IQ as {{ bigip2_target }}"
  when:  clusterName_device1 != clusterName_device2
