---
# Post AS3 declaration to new device using atc_deploy
- name: ATC POST - create new {{ new_tenant_name }}
  include_role:
    name: f5devcentral.atc_deploy
  vars:
    atc_service: AS3
    atc_method: POST
    atc_declaration_file: "{{ dir_as3 }}/{{ new_as3_target }}.json"
    atc_delay: 15
    atc_retries: 30
  register: atc_AS3_status

- name: Populate configSetName array
  set_fact:
    configSetNames_array: "{{ configSetNames_array|default([]) + [ {'name': item } ] }}"
  with_items: "{{ configSetNames }}"

#- debug:
#    var: configSetNames_array

# Move it there using role bigiq_move_app_dashboard
- name: Move AS3 application service(s) in BIG-IQ application dashboard.
  include_role:
    name: f5devcentral.bigiq_move_app_dashboard
  vars:
      apps: 
      - name: "{{ new_bigiq_app_name }}"
        pins: "{{ configSetNames_array }}"
  register: status
