---
- name: Install role from Ansible Galaxy atc_deploy
  command: ansible-galaxy install f5devcentral.atc_deploy
  delegate_to: localhost

- name: Install role from Ansible Galaxy bigiq_move_app_dashboard
  command: ansible-galaxy install f5devcentral.bigiq_move_app_dashboard
  delegate_to: localhost

- name: Install Collection from Ansible Galaxy
  command: ansible-galaxy collection install f5networks.f5_modules
  delegate_to: localhost

#- name: show downloaded roles
#  command: ansible-galaxy list
#  delegate_to: localhost
#  register: galaxy

#- debug:
#    var: galaxy